//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLibXamarin.Scheduling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLibXamarin.Scheduling.Properties.InternalResources", typeof(InternalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be today or later..
        /// </summary>
        internal static string Message_DateMustBeTodayOrLater {
            get {
                return ResourceManager.GetString("Message_DateMustBeTodayOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-monthly style must be set when the semi-monthly period is chosen for a recurring transaction..
        /// </summary>
        internal static string Message_SemiMonthlyStyleMustBeSet {
            get {
                return ResourceManager.GetString("Message_SemiMonthlyStyleMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a correction method is chosen for Saturdays, the recurring transaction cannot begin on a Saturday..
        /// </summary>
        internal static string Message_StartDateCannotBeSaturday {
            get {
                return ResourceManager.GetString("Message_StartDateCannotBeSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a correction method is chosen for Sundays, the recurring transaction cannot begin on a Sunday..
        /// </summary>
        internal static string Message_StartDateCannotBeSunday {
            get {
                return ResourceManager.GetString("Message_StartDateCannotBeSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of the starting date must be the 15th or the last day of the month when selecting the semi-monthly period and the semi-monthly style of &quot;Fifteenth and Last&quot;..
        /// </summary>
        internal static string Message_StartDateMustBeFifteenthOrLast {
            get {
                return ResourceManager.GetString("Message_StartDateMustBeFifteenthOrLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of the starting date must be the 1st or 15th of the month when selecting the semi-monthly period and the semi-monthly style of &quot;First and Fifteenth&quot;..
        /// </summary>
        internal static string Message_StartDateMustBeFirstOrFifteenth {
            get {
                return ResourceManager.GetString("Message_StartDateMustBeFirstOrFifteenth", resourceCulture);
            }
        }
    }
}
